### DISCUSSION TITLE
Sbatch fails due to parameters not being provided (though they are)

### DISCUSSION THREAD

**Discussion by ycsong** [franciscozorrilla/thesis_pipeline#153] [Q&A] [answered]
Hello,

Executing the following code to run metabat:

`bash metaGEM.sh -t metabat -j 1 -c 24 -m 80 -h 10`

I noticed the following in the nohub.out:

```
sbatch: error: You must specify a the number of nodes to use
sbatch: error: Batch job submission failed: Job size specification needs to be provided
Error submitting jobscript (exit code 1):

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/bioinfo_tools/bin/metaGEM/workflow/.snakemake/log/2024-01-10T150739.993699.snakemake.log
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 1
Conda environments: ignored
Job counts:
	count	jobs
	1	all
	1
Select jobs to execute...

[Wed Jan 10 15:12:37 2024]
Job 0: 
        WARNING: Be very careful when adding/removing any lines above this message.
        The metaGEM.sh parser is presently hardcoded to edit line 22 of this Snakefile to expand target rules accordingly,
        therefore adding/removing any lines before this message will likely result in parser malfunction.
```

I find this to be strange, as I've already specified this in the parameter. Also, does metaGEM submits the metabat job to the server using sbatch?

Something I also noticed after executing step is that the jobs don't appear to have been submitted, as when I check with showq or uqueue command, the jobs aren't there. 

Your help would be appreciated as always. Thank you.

**Comment by franciscozorrilla** [comment]
Hey Young,
Yes, the `sbatch` command and `snakemake` are used to submit jobs to the slurm scheduler, for example:
https://github.com/franciscozorrilla/metaGEM/blob/57cfd60485da82438faadcf75edc8623ac822196/workflow/metaGEM.sh#L427
Could you check what version of snakemake you are using? It should be >=5.10.0,<5.31.1.
Also, could you show me what your config files look like? It looks like probably your wildcards are not expanding properly based on the `dataset` folder.

**Comment by ycsong** [comment]
Hi Francisco,

Apologies for the delayed response. Our server was shut down due to a maintenance yesterday. 


The version of snakemake I have at the moment is **5.31.0**

Here is my config.yaml:


```
path:
    root: /home/bioinfo_tools/bin/metaGEM
    scratch: /home/bioinfo_tools/bin/metaGEM/scratch
folder:
    data: dataset
    logs: logs
    assemblies: assemblies
    scripts: scripts
    crossMap: crossMap 
    concoct: concoct
    maxbin: maxbin
    metabat: metabat
    refined: refined_bins
    reassembled: reassembled_bins
    classification: GTDBTk
    abundance: abundance
    GRiD: GRiD
    GEMs: GEMs
    SMETANA: SMETANA
    memote: memote
    qfiltered: qfiltered
    stats: stats
    proteinBins: protein_bins
    dnaBins: dna_bins
    pangenome: pangenome
    kallisto: kallisto
    kallistoIndex: kallistoIndex
    benchmarks: benchmarks
    prodigal: prodigal
    blastp: blastp
    blastp_db: blastp_db
scripts:
    kallisto2concoct: kallisto2concoct.py
    prepRoary: prepareRoaryInput.R
    binFilter: binFilter.py
    qfilterVis: qfilterVis.R
    assemblyVis: assemblyVis.R
    binningVis: binningVis.R
    modelVis: modelVis.R
    compositionVis: compositionVis.R
    taxonomyVis: taxonomyVis.R
    carveme: media_db.tsv
    toy: download_toydata.txt
    GTDBtkVis: 
cores:
    fastp: 4
    megahit: 48
    crossMap: 48
    concoct: 48
    metabat: 48
    maxbin: 48
    refine: 48
    reassemble: 48
    classify: 2
    gtdbtk: 48
    abundance: 16
    carveme: 4
    smetana: 12
    memote: 4
    grid: 24
    prokka: 2
    roary: 12
    diamond: 12
params:
    cutfasta: 10000
    assemblyPreset: meta-sensitive
    assemblyMin: 1000
    concoct: 800
    metabatMin: 50000
    seed: 420
    minBin: 1500
    refineMem: 1600
    refineComp: 50
    refineCont: 10
    reassembleMem: 1600
    reassembleComp: 50
    reassembleCont: 10
    carveMedia: M8
    smetanaMedia: M1,M2,M3,M4,M5,M7,M8,M9,M10,M11,M13,M14,M15A,M15B,M16
    smetanaSolver: CPLEX
    roaryI: 90
    roaryCD: 90
envs:
    metagem: envs/metagem
    metawrap: envs/metawrap
    prokkaroary: envs/prokkaroary
```
